/**
 * Regenerates src/lib/google-fonts.ts from the Google Fonts API.
 *
 * Usage:
 *   GOOGLE_FONTS_API_KEY=your_key tsx scripts/fetch-google-fonts.ts
 *
 * The generated file is committed to the repo. Re-run periodically to pick up
 * new font additions from Google.
 */

import { writeFileSync } from "fs";
import { join } from "path";

const CURATED_FONTS = [
  "Inter", "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", "Nunito",
  "Work Sans", "Plus Jakarta Sans", "Outfit", "Source Sans 3", "Raleway", "Oswald",
  "Merriweather", "Playfair Display", "Libre Baskerville", "Roboto Serif", "DM Serif Text",
  "JetBrains Mono", "Fira Mono", "Azeret Mono",
  "Urbanist",
];

const ICON_FONTS = new Set([
  "Material Icons", "Material Icons Outlined", "Material Icons Round",
  "Material Icons Sharp", "Material Icons Two Tone",
  "Material Symbols Outlined", "Material Symbols Rounded", "Material Symbols Sharp",
  "Noto Color Emoji",
]);

async function main() {
  const apiKey = process.env.GOOGLE_FONTS_API_KEY;
  if (!apiKey) {
    console.error("Error: GOOGLE_FONTS_API_KEY environment variable is required");
    process.exit(1);
  }

  console.log("Fetching Google Fonts catalogue...");
  const url = `https://www.googleapis.com/webfonts/v1/webfonts?key=${apiKey}&sort=popularity`;
  const res = await fetch(url);

  if (!res.ok) {
    console.error(`API error: ${res.status} ${res.statusText}`);
    process.exit(1);
  }

  const data = await res.json() as { items: { family: string }[] };
  const allFonts = data.items
    .map((f) => f.family)
    .filter((name) => !ICON_FONTS.has(name));

  console.log(`Fetched ${allFonts.length} fonts (after filtering icon/emoji fonts)`);

  // Verify all curated fonts are present
  for (const font of CURATED_FONTS) {
    if (!allFonts.includes(font)) {
      console.warn(`Warning: curated font "${font}" not found in API response`);
    }
  }

  const today = new Date().toISOString().split("T")[0];

  const formatArray = (items: string[], indent = 2) =>
    items.map((item) => `${" ".repeat(indent)}${JSON.stringify(item)},`).join("\n");

  const output = `// Auto-generated by scripts/fetch-google-fonts.ts
// Last updated: ${today}
// Source: Google Fonts API (sort=popularity), icon/emoji fonts excluded
// Do not edit manually — run the generation script to update.

/**
 * Hand-curated list of high-quality fonts covering sans-serif, serif, mono,
 * and display categories. Shown by default in the FontPicker.
 */
export const CURATED_FONTS: string[] = [
${formatArray(CURATED_FONTS)}
];

/**
 * Full Google Fonts catalogue sorted by popularity (${allFonts.length} families).
 * Used for full-text search in the FontPicker.
 */
export const ALL_GOOGLE_FONTS: string[] = [
${formatArray(allFonts)}
];
`;

  const outPath = join(import.meta.dirname, "../src/lib/google-fonts.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`Written to ${outPath}`);
  console.log(`Curated: ${CURATED_FONTS.length} fonts`);
  console.log(`Total: ${allFonts.length} fonts`);
}

main();
