/**
 * Regenerates src/lib/google-fonts.ts from the Google Fonts API.
 *
 * Usage:
 *   GOOGLE_FONTS_API_KEY=your_key tsx scripts/fetch-google-fonts.ts
 *
 * The generated file is committed to the repo. Re-run periodically to pick up
 * new font additions from Google or changes to weight availability.
 *
 * What gets regenerated:
 *   - ALL_GOOGLE_FONTS     — full catalogue sorted by popularity
 *   - FONTS_WITH_LIGHT     — Set of font families that have a 300 weight variant
 *
 * What is managed here (not regenerated from API):
 *   - CURATED_FONTS        — hand-curated body font list
 *   - CURATED_HEADING_FONTS — hand-curated heading/display font list
 */

import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { join, dirname } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Hand-curated lists (edit these, then re-run the script) ──────────────────

const CURATED_FONTS = [
  // Sans-serif
  "Inter",
  "Open Sans",
  "Nunito",
  "Work Sans",
  "Plus Jakarta Sans",
  "Raleway",
  "Oswald",
  "Geist",
  "Lexend",
  "Fredoka",
  "Urbanist",
  // Serif
  "Merriweather",
  "Playfair Display",
  "Newsreader",
  // Mono
  "JetBrains Mono",
];

const CURATED_HEADING_FONTS = [
  "Arvo",
  "Bungee",
  "Caveat",
  "Cinzel Decorative",
  "Cookie",
  "Cormorant Garamond",
  "Creepster",
  "Fraunces",
  "IBM Plex Mono",
  "Indie Flower",
  "Inter",
  "Lobster Two",
  "Marvel",
  "Montserrat",
  "Oleo Script",
  "Pacifico",
  "Permanent Marker",
  "Playfair Display",
  "Righteous",
  "Rock Salt",
  "Sacramento",
  "Special Elite",
  "Staatliches",
  "Urbanist",
];

// ─── Icon/emoji fonts to exclude ─────────────────────────────────────────────

const ICON_FONTS = new Set([
  "Material Icons", "Material Icons Outlined", "Material Icons Round",
  "Material Icons Sharp", "Material Icons Two Tone",
  "Material Symbols Outlined", "Material Symbols Rounded", "Material Symbols Sharp",
  "Noto Color Emoji",
]);

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const apiKey = process.env.GOOGLE_FONTS_API_KEY;
  if (!apiKey) {
    console.error("Error: GOOGLE_FONTS_API_KEY environment variable is required");
    process.exit(1);
  }

  console.log("Fetching Google Fonts catalogue...");
  const url = `https://www.googleapis.com/webfonts/v1/webfonts?key=${apiKey}&sort=popularity`;
  const res = await fetch(url);

  if (!res.ok) {
    console.error(`API error: ${res.status} ${res.statusText}`);
    process.exit(1);
  }

  const data = await res.json() as { items: { family: string; variants: string[] }[] };

  const allFonts = data.items
    .map((f) => f.family)
    .filter((name) => !ICON_FONTS.has(name));

  // Fonts that have a genuine 300 (light) weight variant
  const fontsWithLight = data.items
    .filter((f) => !ICON_FONTS.has(f.family) && f.variants.includes("300"))
    .map((f) => f.family);

  console.log(`Fetched ${allFonts.length} fonts (after filtering icon/emoji fonts)`);
  console.log(`Fonts with light (300) weight: ${fontsWithLight.length}`);

  // Verify all curated fonts are present
  const allCurated = [...new Set([...CURATED_FONTS, ...CURATED_HEADING_FONTS])];
  for (const font of allCurated) {
    if (!allFonts.includes(font)) {
      console.warn(`Warning: curated font "${font}" not found in API response`);
    }
  }

  const today = new Date().toISOString().split("T")[0];

  const formatStringArray = (items: string[], indent = 2) =>
    items.map((item) => `${" ".repeat(indent)}${JSON.stringify(item)},`).join("\n");

  const output = `// Auto-generated by scripts/fetch-google-fonts.ts
// Last updated: ${today}
// Source: Google Fonts API (sort=popularity), icon/emoji fonts excluded
// Curated lists are managed in the script itself — edit there, then re-run.

/**
 * Hand-curated list of high-quality fonts covering sans-serif, serif, mono,
 * and display categories. Shown by default in the FontPicker (body variant).
 */
export const CURATED_FONTS: string[] = [
  // Sans-serif
${formatStringArray(CURATED_FONTS.slice(0, 11), 2)}
  // Serif
${formatStringArray(CURATED_FONTS.slice(11, 14), 2)}
  // Mono
${formatStringArray(CURATED_FONTS.slice(14), 2)}
];

/**
 * Hand-curated list for the heading/display font picker.
 * Shown by default when FontPicker variant is "heading".
 */
export const CURATED_HEADING_FONTS: string[] = [
${formatStringArray(CURATED_HEADING_FONTS)}
];

/**
 * Set of Google Font families that include a genuine 300 (Light) weight variant.
 * Used to filter the weight picker so only supported weights are offered.
 * Generated from the Google Fonts API — re-run the script to refresh.
 */
export const FONTS_WITH_LIGHT: ReadonlySet<string> = new Set([
${formatStringArray(fontsWithLight)}
]);

/**
 * Full Google Fonts catalogue sorted by popularity (${allFonts.length} families).
 * Used for full-text search in the FontPicker.
 */
export const ALL_GOOGLE_FONTS: string[] = [
${formatStringArray(allFonts)}
];
`;

  const outPath = join(__dirname, "../src/lib/google-fonts.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`Written to ${outPath}`);
  console.log(`Curated body: ${CURATED_FONTS.length} fonts`);
  console.log(`Curated heading: ${CURATED_HEADING_FONTS.length} fonts`);
  console.log(`Total: ${allFonts.length} fonts`);
}

main();
